User.create!([
  {nombre: "Luis", role_id: 1, email: "lumendez@ipn.mx", encrypted_password: "$2a$11$TQUCkGoQ6Hk1rpBdpAc5keBkFQZZsA6I5Pazd3U/HZ7eC4Xq4NAf6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 206, current_sign_in_at: "2017-04-21 23:34:05", last_sign_in_at: "2017-04-21 22:56:04", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Méndez", materno: "Cruz", rfc: "", centro_id: 1},
  {nombre: "Everardo", role_id: 4, email: "controlescolar@ipn.mx", encrypted_password: "$2a$11$mFADXfnrxfWlOMbFwIph.eWpPgQ/qzp.1vzxI62MnqCSGBHESNOE6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 50, current_sign_in_at: "2017-04-21 22:59:26", last_sign_in_at: "2017-04-21 22:44:29", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "González", materno: "Gómez", rfc: "", centro_id: 1},
  {nombre: "Marco Alberto", role_id: 3, email: "profesor@ipn.mx", encrypted_password: "$2a$11$BEhZQAu/PiLhpejrRaTOmuwSWpvSt0oySdZafXD5iJ7P4J2ZYs8My", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 40, current_sign_in_at: "2017-04-07 23:46:34", last_sign_in_at: "2017-04-06 23:50:51", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Cerecedo ", materno: "Silva", rfc: "CESM760919", centro_id: 1},
  {nombre: "Marlene", role_id: 3, email: "marleneortega@hotmail.com", encrypted_password: "$2a$11$0eMbDQxM.l5TI7NRxQWFIewxpbfcPRP3FxEw0u34dNQ11U4K/ti.m", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 13, current_sign_in_at: "2017-02-08 01:43:00", last_sign_in_at: "2017-01-31 23:09:07", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "::1", paterno: "Ortega", materno: "Aparicio", rfc: nil, centro_id: nil},
  {nombre: "Alberto", role_id: 2, email: "alberto@alberto.com", encrypted_password: "$2a$11$MXFa5TBN9whk..fhyh7MIep8nX3ZtyUNBUJiTAJfqZ1AeQjalSY0q", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2017-04-07 22:18:26", last_sign_in_at: "2017-02-08 01:41:22", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Cruz", materno: "Mendez", rfc: "", centro_id: nil},
  {nombre: "Elvia", role_id: 5, email: "elvia_a_a@hotmail.com", encrypted_password: "$2a$11$.gSbYmIpaDl8pPDNx91lke07RsKNI6hWKA2DI/TI/gi5PSyEzB8lu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2017-03-28 01:37:57", last_sign_in_at: "2017-03-24 02:10:35", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Ángeles", materno: "Aldana", rfc: "", centro_id: 1},
  {nombre: "Dr. Mauro Alberto", role_id: 6, email: "mauro@mauro.com", encrypted_password: "$2a$11$avbgGgAr/9VrQwXP82AjEuk7lS9eCC6Csua67KHO0/GiqtTsu/QZa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 23, current_sign_in_at: "2017-03-16 02:29:40", last_sign_in_at: "2017-03-15 23:59:01", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Enciso", materno: "Aguilar", rfc: "", centro_id: nil},
  {nombre: "Areli", role_id: 3, email: "areli@areli.com", encrypted_password: "$2a$11$PhTunZU8sagsHcdrwiiAneXwX0tUqM7z2BbhdmKl4tlnCmmeBvVPm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:45:07", last_sign_in_at: "2017-02-04 01:45:07", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Pérez", materno: "García", rfc: nil, centro_id: nil},
  {nombre: "Mara", role_id: 3, email: "mara@mara.com", encrypted_password: "$2a$11$ha.jF1W96KApEyD8lpBRRuc/8wZvhf3NohKIkq3lo.AsWx46m4Vg.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:46:38", last_sign_in_at: "2017-02-04 01:46:38", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Ayala", materno: "Samra", rfc: nil, centro_id: nil},
  {nombre: "Irving Antonio", role_id: 3, email: "irving@irving.com", encrypted_password: "$2a$11$HcJPH9SfhFpDWp768S.v6OGZES.lxmZqp4wDK1LRCQy7mQHC51c5K", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:47:28", last_sign_in_at: "2017-02-04 01:47:28", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Barrera", materno: "López", rfc: nil, centro_id: nil},
  {nombre: "Benjamin Manuel", role_id: 3, email: "benjamin@benjamin.com", encrypted_password: "$2a$11$HP3AojkIXcxBS8DSYLI6OuMWdBgaFX6Sk4Jv2.kJzeZz4uO7P/lOu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2017-03-14 02:37:05", last_sign_in_at: "2017-02-08 00:16:56", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Ruiz", materno: "Arreola", rfc: "", centro_id: 1},
  {nombre: "Daniel", role_id: 3, email: "daniel@daniel.com", encrypted_password: "$2a$11$.IPN5n/4rr8fQUuQb.hxweLYkxARjtnIS21aHnXgC85FlM1be/loW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:49:56", last_sign_in_at: "2017-02-04 01:49:56", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Reyes", materno: "Martínez", rfc: nil, centro_id: nil},
  {nombre: "Estephany", role_id: 3, email: "estephany@estephany.com", encrypted_password: "$2a$11$9PBQRgb2WD5kbiOO0gtVOeG4JegbZiZVaS8t3cuxR3hRrATyYHjY.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:51:19", last_sign_in_at: "2017-02-04 01:51:19", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Vega", materno: "Rendón", rfc: nil, centro_id: nil},
  {nombre: "Irineo Luz", role_id: 3, email: "irineo@irineo.com", encrypted_password: "$2a$11$y3Wp6KGeYIsNBd5ZtzaeYeuQgqn7RkylFjlaidA6VaFsS/IDMdz9i", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-04-06 23:52:23", last_sign_in_at: "2017-02-04 01:52:09", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "::1", paterno: "Vidal", materno: "Reyes", rfc: nil, centro_id: nil},
  {nombre: "Leonor", role_id: 3, email: "leonor@leonor.com", encrypted_password: "$2a$11$D9cKXUy2Q5iCh2CGxg2PvOTEz9/oLyZuPnesH4LGCmr4BKs9B6HYa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2017-04-04 23:20:10", last_sign_in_at: "2017-02-25 02:24:43", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Flores", materno: "Olvera", rfc: "", centro_id: 1},
  {nombre: "Luis Humberto", role_id: 3, email: "luis@molina.com", encrypted_password: "$2a$11$6IVAr.K5EJpdcIke8WWtQOH8LD059jgKDeae/HLmAoFp2pvzTZbVW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:53:25", last_sign_in_at: "2017-02-04 01:53:25", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Molina", materno: "Navarrete", rfc: nil, centro_id: nil},
  {nombre: "María Belén", role_id: 3, email: "maria@belen.com", encrypted_password: "$2a$11$tiiHIWoEyQ3gK3G7SFuwHOTLmgUZdSGi7iRKJL/BImLeQfj44qX2S", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:54:24", last_sign_in_at: "2017-02-04 01:54:24", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Vázquez", materno: "Conde", rfc: nil, centro_id: nil},
  {nombre: "Maribel", role_id: 3, email: "maribel@santiago.com", encrypted_password: "$2a$11$1wLVl7yxN4uPTiz2wI4Oy.WnZsFSBtfZx2iD7baO0ifWwnjYvtU9W", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:55:42", last_sign_in_at: "2017-02-04 01:55:42", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Santiago", materno: "Martínez", rfc: nil, centro_id: nil},
  {nombre: "Nadia", role_id: 3, email: "nadia@aguirre.com", encrypted_password: "$2a$11$J5XKwm7ZrszbVo7cnaHnne8Pv2IUM3vbWvzpxPH30QOK73cAf9Lta", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:56:24", last_sign_in_at: "2017-02-04 01:56:24", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Aguirre", materno: "Ortíz", rfc: nil, centro_id: nil},
  {nombre: "Eunice", role_id: 3, email: "eunice@eunice.com", encrypted_password: "$2a$11$mWfafbPxaxnHtjJBqB881OpWX3I0AX9Mr06tiEmH2nLz//XaLHFAq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:56:53", last_sign_in_at: "2017-02-04 01:56:53", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Villanueva", materno: "Flores", rfc: nil, centro_id: nil},
  {nombre: "Luis", role_id: 3, email: "luis@villanueva.com", encrypted_password: "$2a$11$04Q8lEqZUdoc6/h6d1uLRO7JZhO.flXk6Z/FmJlPw3297J77fuS0C", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-04 01:58:31", last_sign_in_at: "2017-02-04 01:58:31", current_sign_in_ip: "::1", last_sign_in_ip: "::1", paterno: "Villanueva", materno: "García", rfc: nil, centro_id: nil},
  {nombre: "Hugo", role_id: 2, email: "hugo@barrios.com", encrypted_password: "$2a$11$cNegvIpnvWXYyuytdl88ROqgEUgMxVGgMHs6j/nNqY.l5tM2wyKLu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2017-04-06 23:12:30", last_sign_in_at: "2017-04-05 23:18:45", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Barrios", materno: "de Jesús", rfc: nil, centro_id: nil},
  {nombre: "Luis Alberto", role_id: 2, email: "luis@hernandez.com", encrypted_password: "$2a$11$I/KuGYIJHEl.4g9by18nk.ZasLW//3kMRNhXJ5Fa5/jQYubAbV9SS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:29:23", last_sign_in_at: "2017-02-09 00:39:56", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Hernández", materno: "Calderón", rfc: nil, centro_id: nil},
  {nombre: "David", role_id: 2, email: "david@carrasco.com", encrypted_password: "$2a$11$.gN9JxQsjCPKeS2lIL2.keOEjgdHPUCStOPf4ffEafWA0SGG5NNte", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:30:22", last_sign_in_at: "2017-02-09 00:40:44", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Carrasco", materno: "Rojas", rfc: nil, centro_id: nil},
  {nombre: "Beatriz Adriana", role_id: 2, email: "beatriz@cruz.com", encrypted_password: "$2a$11$OGGjhcONN6elGZy1lBg3C.S1fJvcYqd1BR92LXI4HSgCDtZb3lm6q", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 11, current_sign_in_at: "2017-04-05 22:58:39", last_sign_in_at: "2017-04-05 22:28:41", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Cruz", materno: "Gutiérrez", rfc: "", centro_id: 1},
  {nombre: "Martha Judith", role_id: 2, email: "martha@duenas.com", encrypted_password: "$2a$11$M0Lg.3m1ZSQbWaAFzDfMneDOB7QziaFsbGXyeEUq/CKwqDh68goVq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-09 01:04:04", last_sign_in_at: "2017-02-09 01:04:04", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Dueñas", materno: "Baca", rfc: nil, centro_id: nil},
  {nombre: "Mariano", role_id: 2, email: "mariano@fernandez.com", encrypted_password: "$2a$11$VExyQoX5GwghPB1qmS1K/.CWgDDtJ.2e.aCSiPNqOY7gXmSYvAIkq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2017-03-07 00:26:35", last_sign_in_at: "2017-03-07 00:25:26", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Fernández", materno: "Rosas", rfc: nil, centro_id: nil},
  {nombre: "Miguel Ángel", role_id: 2, email: "miguel@garcia.com", encrypted_password: "$2a$11$OfI6U1OLT1F6dAviBsI0U.ifz8ydhjHg3ApJE2l9XR2w/rcngyvYe", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:37:29", last_sign_in_at: "2017-02-09 01:05:57", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "García", materno: "Gómez", rfc: nil, centro_id: nil},
  {nombre: "Moisés", role_id: 2, email: "moises@garcia.com", encrypted_password: "$2a$11$klvmt1bRTeRr7DHEObZaxu4a80xlj0WTk8IohZ0AuqeI8bTUvr95S", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:39:23", last_sign_in_at: "2017-02-09 01:10:03", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "García", materno: "Pineda", rfc: nil, centro_id: nil},
  {nombre: "Marisela", role_id: 2, email: "marisela@gomez.com", encrypted_password: "$2a$11$EZh1GPM.QNcDeDFo8GVHjuZrtUZ08gEvSLgV2fmmDXwLdo4qjPaV2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2017-03-10 23:39:16", last_sign_in_at: "2017-03-07 00:33:50", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Gómez", materno: "Maldonado", rfc: nil, centro_id: nil},
  {nombre: "Eduardo", role_id: 2, email: "eduardo@gonzalez.com", encrypted_password: "$2a$11$uZwzYu/nzpijafLftehpp.SFlVmSdauOw8zO/.2N2nOSnVw4/O8r.", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:45:36", last_sign_in_at: "2017-02-09 01:11:34", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "González", materno: "Medina", rfc: nil, centro_id: nil},
  {nombre: "Yosselin", role_id: 2, email: "yosselin@guevara.com", encrypted_password: "$2a$11$ryQ06vQzI0ayy0l/GfFq2uGCGRkcY.Nqbm1y/2h9b599eu9PK9nUO", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:46:15", last_sign_in_at: "2017-02-09 01:12:24", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Guevara", materno: "de Gante", rfc: nil, centro_id: nil},
  {nombre: "Rogelio", role_id: 2, email: "rogelio@hernandez.com", encrypted_password: "$2a$11$8szNpGAOJagYtwGY6ggpeugk9n3rcbBHSW9xazmSMTuFr62jUv2dW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:46:52", last_sign_in_at: "2017-02-09 01:13:34", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Hernández", materno: "Martínez", rfc: nil, centro_id: nil},
  {nombre: "Sandra Susana", role_id: 2, email: "sandra@martinez.com", encrypted_password: "$2a$11$o89uONuUXzgbcX9b272PjuEinSlF8nxkvejwPzSD69xpg8VRh8cbi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:47:26", last_sign_in_at: "2017-02-09 01:14:21", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Martínez", materno: "Castro", rfc: nil, centro_id: nil},
  {nombre: "Gloria", role_id: 2, email: "gloria@mata.com", encrypted_password: "$2a$11$SMjSEfIa3OmDukMt42e67OwZegNHrYLr.7RruBpjWeaemG5ANOmQi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:49:01", last_sign_in_at: "2017-02-09 01:15:00", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Mata", materno: "Miranda", rfc: nil, centro_id: nil},
  {nombre: "José Antonio", role_id: 2, email: "jose@medina.com", encrypted_password: "$2a$11$5.iXe3IY.WBf0nx5W2yWkODmC7Gci9YZQDDPF8ACYzN3PWtMmey.O", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 8, current_sign_in_at: "2017-02-28 23:13:56", last_sign_in_at: "2017-02-28 02:07:43", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Medina", materno: "Valdéz", rfc: nil, centro_id: nil},
  {nombre: "Teresa del Carmen", role_id: 2, email: "teresa@parra.com", encrypted_password: "$2a$11$KRHApxR0v4ett/xfVkVkyOxPOpvQ58Ad60ch86cib.JFHhs4/QrAi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:50:48", last_sign_in_at: "2017-02-09 01:18:47", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Parra", materno: "Toledo", rfc: nil, centro_id: nil},
  {nombre: "Daniela", role_id: 2, email: "daniela@patino.com", encrypted_password: "$2a$11$oJAddOi10uIIPU3pJ6M7H.4XIzKVSU6ygh0LnCVVnLARQQ.gdSlTK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:55:52", last_sign_in_at: "2017-02-09 01:21:10", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Patiño", materno: "Pérez", rfc: nil, centro_id: nil},
  {nombre: "Julio César", role_id: 2, email: "julio@ramirez.com", encrypted_password: "$2a$11$.3YDI5BQqECT/rMD/2kbVuvCBZEpXohwBCGV4vJDrn7KzOs4qGQ8i", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:56:28", last_sign_in_at: "2017-02-09 01:22:50", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Ramírez", materno: "Hernández", rfc: nil, centro_id: nil},
  {nombre: "Héctor", role_id: 2, email: "hector@ramirez.com", encrypted_password: "$2a$11$L2SQW7NUe10fLgF8UrN58uACx3ndFI33uDKqIDGAweycxzUzfRiyq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2017-04-07 23:31:33", last_sign_in_at: "2017-02-09 01:58:21", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Ramírez", materno: "Vázquez", rfc: nil, centro_id: nil},
  {nombre: "Marcela del Carmen", role_id: 2, email: "marcela@sanchez.com", encrypted_password: "$2a$11$XRQN46xumly.LAfqxFbM/.GdQBYpBrliPIET9rFEL59hATO0gCYJy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-09 01:58:56", last_sign_in_at: "2017-02-09 01:24:18", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Sánchez", materno: "Chávez", rfc: nil, centro_id: nil},
  {nombre: "Alberto Luis", role_id: 4, email: "alberto@cruz.com", encrypted_password: "$2a$11$1R.FQNrMEx7ixJxVWVNSYunA.bfYP75VjCjOyzzoHSfJzhxJHBmI6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 6, current_sign_in_at: "2017-02-24 01:00:02", last_sign_in_at: "2017-02-24 00:45:35", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Méndez", materno: "Cruz", rfc: "MCAL850121", centro_id: nil},
  {nombre: "Gerardo", role_id: 2, email: "grarr1533@gmail.com", encrypted_password: "$2a$11$JhY/pOYmKe/wTd5OrNLe2.nbBcoK.AOF0p5Em1xYGk/NtHbX/3.fm", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-02-28 00:57:54", last_sign_in_at: "2017-02-25 01:30:50", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Arreola", materno: "Ramírez", rfc: "AERG990220", centro_id: nil},
  {nombre: "Edgar Ulises", role_id: 2, email: "edgar-upiicsa@hotmail.com", encrypted_password: "$2a$11$9nQHSW5tInY8mELO.F2PiOAyWbhDxoyvpQjlVBbpIOs5yRu/E3XtK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 01:58:04", last_sign_in_at: "2017-02-25 01:58:04", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Campos", materno: "Montes", rfc: "CAME921002", centro_id: nil},
  {nombre: "Elías Salomón", role_id: 2, email: "elias_salomon@live.com.mx", encrypted_password: "$2a$11$m/kcVBS8l8oq16h1KP2iD.oarFWck0HTMHB5cyNN9YmOKz.t6dfiW", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:00:19", last_sign_in_at: "2017-02-25 02:00:19", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Cruz", materno: "Molina", rfc: "", centro_id: nil},
  {nombre: "André Bernardo", role_id: 2, email: "andrefrancia@live.com.mx", encrypted_password: "$2a$11$ExRZ4o0I.MjoC4MtrYPdYuekO0DaugbXprKYCHZsgTf3vaCJgsAyC", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:03:28", last_sign_in_at: "2017-02-25 02:03:28", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "García", materno: "Álvarez", rfc: "GAAA940825", centro_id: nil},
  {nombre: "Boris Agustín", role_id: 2, email: "boristorre@yahoo.com.mx", encrypted_password: "$2a$11$.Wlc02q3kGLXtIzuedz5o.pM9VcqxvrOB4df1Qc8jlon2zDJhxveq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:06:21", last_sign_in_at: "2017-02-25 02:06:21", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "García", materno: "Torres", rfc: "GATB930122", centro_id: nil},
  {nombre: "José Benito", role_id: 2, email: "jose@benito.com", encrypted_password: "$2a$11$eBHKhDEpMmavTpVbvd/zuujBvOfgOxXTUXFShuo5DFndrIWvu0t1e", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:08:05", last_sign_in_at: "2017-02-25 02:08:05", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Gutiérrez", materno: "Álvarado", rfc: "", centro_id: nil},
  {nombre: "Daniela", role_id: 2, email: "dani_2300@hotmail.com", encrypted_password: "$2a$11$JDNDhFgd8fUE/qAE.Pws3Oglw22HClV/aerbnzd0ow/pqm3fSdCYa", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:09:43", last_sign_in_at: "2017-02-25 02:09:43", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Luna", materno: "Álvarez", rfc: "LUAD000916", centro_id: nil},
  {nombre: "Javier", role_id: 2, email: "javier301912@gmail.com", encrypted_password: "$2a$11$U6hHNm8G.Gj34YmMMECYBukcOfPZYPciIyLlKcOTdLLV.YaYtypGi", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:11:31", last_sign_in_at: "2017-02-25 02:11:31", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Martínez", materno: "Prado", rfc: "MAPJ970204", centro_id: nil},
  {nombre: "José Antonio", role_id: 2, email: "antoniovl.94@hotmail.com", encrypted_password: "$2a$11$tdt2O3jEYEOf5N/gE1xcmu/EzpcLhrc44r7IWM9eSXrcINzKar/Ly", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:13:07", last_sign_in_at: "2017-02-25 02:13:07", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Moguel", materno: "Ibarra", rfc: "MOIA940924", centro_id: nil},
  {nombre: "Wendy Itzayán", role_id: 2, email: "motriz14@hotmail.com", encrypted_password: "$2a$11$CnU4QH716PSnUYEMlhs8HuWzr9TSq2o3oyrSEnWcMeT1Vmlj0D0UG", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:15:02", last_sign_in_at: "2017-02-25 02:15:02", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Oropeza", materno: "Rodríguez", rfc: "OORW940312", centro_id: nil},
  {nombre: "Brenda Isabel", role_id: 2, email: "brendaisabel@hotmail.com", encrypted_password: "$2a$11$lb0jZ2m599i77u.o86TjqOJoFGi0PCQp6DUu6PGnSS2hWsHf10Dem", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:16:47", last_sign_in_at: "2017-02-25 02:16:47", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Pérez", materno: "Serrano", rfc: "PESB810226", centro_id: nil},
  {nombre: "Ana Damariz", role_id: 2, email: "adamarizpz@hotmail.com", encrypted_password: "$2a$11$/OPXA2oVy8nnFMwl4sqkVOpwukeRXZ2EHSvmxJNUz5aRVbEK6SZcq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:19:01", last_sign_in_at: "2017-02-25 02:19:01", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Pérez", materno: "Zaragoza", rfc: "PEZA810208", centro_id: nil},
  {nombre: "Erik", role_id: 2, email: "erikrojo123@hotmail.com", encrypted_password: "$2a$11$ypBDziFk3gNtBH3odFVRv.BbFBBqYMudLnN6Q5/5Zoz6sNVSpSk3q", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 9, current_sign_in_at: "2017-03-16 02:17:45", last_sign_in_at: "2017-03-16 02:02:48", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Romero", materno: "Castillo", rfc: "ROCE870318", centro_id: nil},
  {nombre: "Alma Nidia", role_id: 2, email: "pinchon.color@gmail.com", encrypted_password: "$2a$11$sW0BRLByQOLd0IkUUCs/UutjkWEAz/JFN.jF6G8ftlEQumyvQuwva", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:22:18", last_sign_in_at: "2017-02-25 02:22:18", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Villa", materno: "Rangel", rfc: "VIRA890719", centro_id: nil},
  {nombre: "Karen Raquel", role_id: 2, email: "huiloka.glam@gmail.com", encrypted_password: "$2a$11$QD1XM05b3WKAOCMPr6DUTefL1hyUsMvdkRQX5nBhvwil7I4t2jGVK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-25 02:23:59", last_sign_in_at: "2017-02-25 02:23:59", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Huilotl", materno: "Belmares", rfc: "HUBK961230", centro_id: nil},
  {nombre: "José Benito", role_id: 2, email: "malvarez@hotmail.com", encrypted_password: "$2a$11$OukS2.4u3s3pMyCDjUNjs..RO9yN.HzqSRjXy0js2kr55BBCj.2w6", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-02-28 01:09:24", last_sign_in_at: "2017-02-28 01:09:24", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Martínez", materno: "Álvarez", rfc: "MAAJ880507", centro_id: nil},
  {nombre: "Daniela", role_id: 2, email: "daniela@moguel.com", encrypted_password: "$2a$11$vgZzlCavoftllfSfxiiK7OIIDiud1.7sKBdIKPuxIHf9c2QoyoUWC", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2017-02-28 02:29:08", last_sign_in_at: "2017-02-28 02:14:56", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Moguel", materno: "Prado", rfc: "MOPD750822", centro_id: nil},
  {nombre: "Mariano", role_id: 2, email: "marianopineda@hotmail.com", encrypted_password: "$2a$11$hgT36voxctxG.KGlJb21feWYwKs04whAlfZPxNolZQbiGIHGGIkmK", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 1, current_sign_in_at: "2017-03-02 00:26:23", last_sign_in_at: "2017-03-02 00:26:23", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Pineda", materno: "Gómez", rfc: "PIGM871212", centro_id: nil},
  {nombre: "Angelica", role_id: 2, email: "angy8701@outlook.com", encrypted_password: "$2a$11$Idpyx1F9aJ2tTppt7gFGvu2rC/a93zF1d5P.V95YW9UAFwifBoU.2", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 5, current_sign_in_at: "2017-03-02 03:00:30", last_sign_in_at: "2017-03-02 02:31:01", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Torres", materno: "Torres", rfc: "TOTA870101", centro_id: nil},
  {nombre: "Daniela", role_id: 2, email: "daniela@matias.com", encrypted_password: "$2a$11$X0RNQrjeGnlWulRQdUiIWOwv/UaSbHv2Pl8z23PivJQfMaDCPwH5u", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2017-03-03 00:09:43", last_sign_in_at: "2017-03-03 00:06:55", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Matías", materno: "de Gante", rfc: "MAGD881220", centro_id: nil},
  {nombre: "Mariano", role_id: 2, email: "mariano@hernandez.com", encrypted_password: "$2a$11$Ym1u.A296NluuR6DrcPVMeRHcgWD1M2XhV7qdH7xZ0N3JnY99uaJu", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-04-17 23:19:48", last_sign_in_at: "2017-03-03 00:10:38", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Hernández", materno: "Reyes", rfc: "HERM901212", centro_id: nil},
  {nombre: "Rogelio", role_id: 2, email: "rogelio@campos.com", encrypted_password: "$2a$11$AWD4XIq2KcUZIolHkArxxODANHowsTTTGtK/4jlz95OB/9uNojFNS", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-03-07 00:23:59", last_sign_in_at: "2017-03-07 00:19:27", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Campos", materno: "Maldonado", rfc: "MACR901221", centro_id: nil},
  {nombre: "Marisela", role_id: 2, email: "marisela@pineda.com", encrypted_password: "$2a$11$cvfmn5XHdRu9GI4r.2qZt.LXOwYrVorgjj62ifOdNP8Mn95VQDorq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 2, current_sign_in_at: "2017-03-07 00:34:21", last_sign_in_at: "2017-03-07 00:27:41", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Pineda", materno: "Gómez", rfc: "GOPM891213", centro_id: nil},
  {nombre: "Hugo", role_id: 2, email: "hugo@rojas.com", encrypted_password: "$2a$11$pJfDyYANN7lcuq//jdbSaONkcPoP7w3CsP.fnMGGy755BEAM1qeAy", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 7, current_sign_in_at: "2017-03-16 23:33:19", last_sign_in_at: "2017-03-15 23:46:53", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Rojas", materno: "Cruz", rfc: "CRRH901212", centro_id: 1},
  {nombre: "Julio", role_id: 2, email: "julio@mata.com", encrypted_password: "$2a$11$0kNw9OklkEOMGGJZTeX3v.Mef064Opge01EJ8xWxQ8rA8HmcAFQ4q", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 3, current_sign_in_at: "2017-03-28 01:38:30", last_sign_in_at: "2017-03-16 23:30:16", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Mata", materno: "Martínez", rfc: "MAMJ701017", centro_id: 1},
  {nombre: "Ana Laura", role_id: 7, email: "coordinadoracelex.cec-iemd@outlook.com", encrypted_password: "$2a$11$qoaZQTk6oW4hCDCSk8xgqe2xtKbwChXjgWi2JlACGg3gP/LceHSyq", reset_password_token: nil, reset_password_sent_at: nil, remember_created_at: nil, sign_in_count: 4, current_sign_in_at: "2017-04-22 00:07:31", last_sign_in_at: "2017-04-20 23:30:18", current_sign_in_ip: "127.0.0.1", last_sign_in_ip: "127.0.0.1", paterno: "Díaz", materno: "Barroso", rfc: "DIBA890310", centro_id: 1}
])
Calendario.create!([
  {nombre: "Intensivo A", registro: "9-Ene,14-Ene", examen_colocacion: "9-Ene,14-Ene", inicio_curso: "16-Ene", examen_medio: "27-Ene", examen_final: "9-Feb", entrega_boletas: "10-Feb", suspension_labores: "", vacaciones: "", periodo: "16 - Enero,10 - Febrero", anio: "2017", estado: "Cerrado"},
  {nombre: "Intensivo B", registro: "13-Feb,17-Feb", examen_colocacion: "13-Feb,17-Feb", inicio_curso: "20-Feb", examen_medio: "3-Mar", examen_final: "9-Feb", entrega_boletas: "17-Feb", suspension_labores: "", vacaciones: "", periodo: "20 - Febrero,17 - Marzo", anio: "2017", estado: "Abierto"},
  {nombre: "Intensivo C", registro: "20-Mar,24-Mar", examen_colocacion: "20-Mar,24-Mar", inicio_curso: "27-Mar", examen_medio: "7-Abr", examen_final: "28-Abr", entrega_boletas: "29-Abr", suspension_labores: "", vacaciones: "10-Abr,16-Abr", periodo: "27 - Marzo,29 - Abril", anio: "2017", estado: "Abierto"},
  {nombre: "Intensivo D", registro: "2-May,4-May", examen_colocacion: "2-May,4-May", inicio_curso: "8-May", examen_medio: "23-May", examen_final: "5-Jun", entrega_boletas: "6-Jun", suspension_labores: "5-May", vacaciones: "", periodo: "8 - Mayo,6 - Junio", anio: "2017", estado: "Cerrado"},
  {nombre: "Intensivo E", registro: "7-Jun,9-Jun", examen_colocacion: "7-Jun,9-Jun", inicio_curso: "12-Jun", examen_medio: "23-Jun", examen_final: "6-Jul", entrega_boletas: "7-Jul", suspension_labores: "", vacaciones: "", periodo: "12 - Junio,7 - Julio", anio: "2017", estado: "Cerrado"},
  {nombre: "Verano 1", registro: "3-Jul,7-Jul", examen_colocacion: "3-Jul,7-Jul", inicio_curso: "10-Jul", examen_medio: "13-Jul", examen_final: "19-Jul", entrega_boletas: "19-Jul", suspension_labores: "", vacaciones: "", periodo: "10 - Julio,19 - Julio", anio: "2017", estado: "Cerrado"},
  {nombre: "Verano 2", registro: "20-Jul,21-Jul", examen_colocacion: "20-Jul,21-Jul", inicio_curso: "24-Jul", examen_medio: "27-Jul", examen_final: "2-Ago", entrega_boletas: "2-Ago", suspension_labores: "", vacaciones: "", periodo: "24 - Julio,2 - Agosto", anio: "2017", estado: "Cerrado"},
  {nombre: "Intensivo F", registro: "1-Ago,4-Ago", examen_colocacion: "1-Ago,4-Ago", inicio_curso: "7-Ago", examen_medio: "18-Ago", examen_final: "31-Ago", entrega_boletas: "1-Sep", suspension_labores: "", vacaciones: "", periodo: "7 - Agosto,1 - Septiembre", anio: "2017", estado: "Cerrado"},
  {nombre: "Intensivo G", registro: "4-Sep,8-Sep", examen_colocacion: "4-Sep,8-Sep", inicio_curso: "11-Sep", examen_medio: "22-Sep", examen_final: "5-Oct", entrega_boletas: "6-Oct", suspension_labores: "", vacaciones: "", periodo: "11 - Septiembre,6 - Octubre", anio: "2017", estado: "Cerrado"},
  {nombre: "Intensivo H", registro: "9-Oct,13-Oct", examen_colocacion: "9-Oct,13-Oct", inicio_curso: "16-Oct", examen_medio: "27-Oct", examen_final: "13-Nov", entrega_boletas: "14-Nov", suspension_labores: "", vacaciones: "", periodo: "16 - Octubre,14 - Noviembre", anio: "2017", estado: "Cerrado"},
  {nombre: "Sabatino 1", registro: "9-Ene,20-Ene", examen_colocacion: "9-Ene,20-Ene", inicio_curso: "21-Ene", examen_medio: "11-Feb", examen_final: "11-Mar", entrega_boletas: "11-Mar", suspension_labores: "", vacaciones: "", periodo: "21 - Enero al 11 - Marzo", anio: "2017", estado: "Abierto"}
])
Centro.create!([
  {nombre: "Ingeniero Eugenio Méndez Docurro", direccion: nil, telefono: nil, extension: nil, lugar: "Ciudad de México"},
  {nombre: "Cajeme", direccion: "Blvd. Rodolfo Elias Calles No. 216, Col. Campestre, C.P. 85160", telefono: "57296000", extension: "00000", lugar: "Ciudad Obregón, Sonora"},
  {nombre: "Campeche", direccion: "Calle 55 No. 1, Col. Centro, C.P. 24000", telefono: "57296000", extension: "00000", lugar: "Campeche, Campeche"},
  {nombre: "Clúster Politécnico Chihuahua", direccion: "Av. Instituto Politécnico Nacional esq. Florida, Col. Quinta del Sol, C.P. 31250", telefono: "57296000", extension: "00000", lugar: "Chihuahua, Chihuahua"},
  {nombre: "Culiacán", direccion: "Antonio Rosales No. 412 Pte. esq. Donato Guerra, Col. Centro, C.P. 8000", telefono: "57296000", extension: "00000", lugar: "Culiacán, Sinaloa"},
  {nombre: "Durango", direccion: "\"Biblioteca Municipal\" Blvd. Dolores del Rio S/N, Col. Analco, C.P. 34076", telefono: "57296000", extension: "00000", lugar: "Durango, Durango"},
  {nombre: "Hidalgo", direccion: "Camerino Mendoza No. 318, Col. Morelos, C.P. 42040", telefono: "57296000", extension: "00000", lugar: "Pachuca, Hidalgo"},
  {nombre: "Mazatlán", direccion: "\"Edificio Palacio Federal\" Benito Juárez s/n entre Ángel Flores y 21 de Marzo, Col. Centro, C.P. 82000", telefono: "57296000", extension: "00000", lugar: "Mazatlán, Sinaloa"},
  {nombre: "Los Mochis", direccion: "Rubí S/N esq. Blvd. Macapule, Fraccionamiento Viñefos, C.P. 81228", telefono: "57296000", extension: "00000", lugar: "Los Mochis, Sinaloa"},
  {nombre: "Morelia", direccion: "Calle de la Arboleda No. 200, Col. Exhacienda San José de la Huerta, C.P. 58190", telefono: "57296000", extension: "00000", lugar: "Morelia, Michoacán"},
  {nombre: "Morelos", direccion: "\"Parque Científico y Tecnológico Morelos i+D\" Torre Norte, 3er. Piso, Autopista Cuernavaca-Acapulco Km. 112, C.P. 62797", telefono: "57296000", extension: "00000", lugar: "Xochitepec, Morelos"},
  {nombre: "Oaxaca", direccion: "Calle Hornos No. 1003, Col. Santa Cruz XOxocotlán, C.P. 71230", telefono: "57296000", extension: "00000", lugar: "Santa Cruz Xoxocatlán, Oaxaca"},
  {nombre: "Reynosa", direccion: "Blvd. del Maestro s/n esq. Elias Piña, Col. Narciso Mendoza, C.P. 88710", telefono: "57296000", extension: "00000", lugar: "Reynosa, Tamaulipas"},
  {nombre: "Tampico", direccion: "Guerrero No. 2 esq. Torreón, Col. Campbell, C.P. 89260", telefono: "57296000", extension: "00000", lugar: "Tampico, Tamaulipas"},
  {nombre: "Tijuana", direccion: "A. del Parque No. 1210, Col. Mesa de Otay, C.P. 22510", telefono: "57296000", extension: "00000", lugar: "Tijuana, Baja California"},
  {nombre: "Tlaxcala", direccion: "Av. Melchor Ocampo No. 28, Col. San Pablo Apetatitlán, C.P. 906000", telefono: "57296000", extension: "00000", lugar: "Apetatitlán, Tlaxcala"},
  {nombre: "Clúster Politécnico Veracruz", direccion: "Calle Azueta No. 204, Col. Centro Papantla, C.P. 93400", telefono: "57296000", extension: "00000", lugar: "Papantla, Veracruz"},
  {nombre: "Cancún", direccion: "Blvd. Kukulkán Km. 12.5, Centro Empresarial Cancún, Torre A 1er. Piso, Zona Hotelera, C.P. 77500 ", telefono: "57296000", extension: "00000", lugar: "Cancún, Quintana Roo"}
])
ClaveCatalogo.create!([
  {nombre: "0861/0863"},
  {nombre: "0853/0854"}
])
CuotaCurso.create!([
  {nombre: "$1125.50/$1382.00", descripcion: "Cuota para el público en general"},
  {nombre: "$493.50/$985.50", descripcion: "Cuota para la comunidad politécnica"}
])
Cuotum.create!([
  {cuota: "493.5"},
  {cuota: "909.5"},
  {cuota: "955.5"},
  {cuota: "985.5"},
  {cuota: "1125.5"},
  {cuota: "1328.5"}
])
Curriculum.create!([
  {calle: "Avenida San Pablo 396", colonia: "San Martin Xochinahuac", municipui: "Azcapotzalco", entidad: "Ciudad de México", correo: "lumendez@ipn.mx", telefono: "57296000", celular: "5513771496", lugar: "Ciudad de México", foto_file_name: "foto_infantil-500x500.jpg", foto_content_type: "image/jpeg", foto_file_size: 75058, foto_updated_at: "2017-03-11 02:45:09", user_id: 1, nombre: "Luis", paterno: "Méndez", materno: "Cruz"}
])
CursoNombre.create!([
  {nombre: "Intensivo A"},
  {nombre: "Intensivo B"},
  {nombre: "Intensivo C"},
  {nombre: "Intensivo D"},
  {nombre: "Intensivo E"},
  {nombre: "Intensivo F"},
  {nombre: "Intensivo G"},
  {nombre: "Intensivo H"},
  {nombre: "Intensivo I"},
  {nombre: "Verano 1"},
  {nombre: "Verano 2"},
  {nombre: "Verano 3"},
  {nombre: "Sabatino 1"},
  {nombre: "Sabatino 2"},
  {nombre: "Sabatino 3"},
  {nombre: "Sabatino 4"},
  {nombre: "Sabatino 5"}
])
DatosBanco.create!([
  {nombre: "BBVA Bancomer", cuenta: "0168358273", referencia: "", titular: "Fondo de Investigación Científica y Desarrollo Tecnológico del IPN"}
])
Estado.create!([
  {nombre: "Pendiente"},
  {nombre: "Abierto"},
  {nombre: "Cerrado"}
])
ExamenColocacionIdioma.create!([
  {nombre: "Fulanito", paterno: "Pérez", materno: "X", idioma: "Inglés", nivel_asignado: "", examinador: "", imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: nil}
])
Genero.create!([
  {genero: "Femenino"},
  {genero: "Masculino"}
])
Grupo.create!([
  {nombre: "Inglés | Intermedio 5 | 07:00-09:00 | Intensivo B", profesor_nombre_id: 1, horario: "07:00-09:00", idioma: "Inglés", nivel: "Intermedio 5", estado: "Cerrado", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 8, lugar: "Ciudad de México", fecha: "10 de enero", centro: "Ingeniero Eugenio Méndez Docurro", tipo: "Curso", modalidad: "Presencial", cupo: "10", duracion: "40 horas", cuota: "$493.50/$985.50", clave: "0853/0854", proyecto: "Cursos extracurriculares de lenguas extranjeras", institucion_bancaria: "BBVA Bancomer", cuenta: "0168358273", titular: "Fondo de investigación científica y desarrollo tecnológico del IPN", instructor: "8", instructor_rfc: "8", instructor_correo: "8", jefe_ec: "M. en C. Elvia Ángeles Aldana", registro: "DFLE-CELEX02I-Act-15", referencia: "", habilitar_constancias_grupo: true},
  {nombre: "Italiano | Básico 1 | 07:00-09:00 | Intensivo B", profesor_nombre_id: 1, horario: "07:00-09:00", idioma: "Italiano", nivel: "Básico 1", estado: "Cerrado", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 15, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 1 | 09:00-11:00 | Intensivo B", profesor_nombre_id: 1, horario: "09:00-11:00", idioma: "Inglés", nivel: "Básico 1", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 21, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "Elvia Ángeles Aldana", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Avanzado 4 | 09:00-11:00 | Intensivo A", profesor_nombre_id: 1, horario: "09:00-11:00", idioma: "Inglés", nivel: "Avanzado 4", estado: "Cerrado", curso: "Intensivo A", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 20, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 1 | 11:00-13:00 | Intensivo B", profesor_nombre_id: 1, horario: "11:00-13:00", idioma: "Inglés", nivel: "Básico 1", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 23, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 2 | 11:00-13:00 | Intensivo A", profesor_nombre_id: 1, horario: "11:00-13:00", idioma: "Inglés", nivel: "Básico 2", estado: "Cerrado", curso: "Intensivo A", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 21, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 5 | 13:00-15:00 | Intensivo A", profesor_nombre_id: 1, horario: "13:00-15:00", idioma: "Inglés", nivel: "Básico 5", estado: "Cerrado", curso: "Intensivo A", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 20, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 5 | 15:00-17:00 | Intensivo B", profesor_nombre_id: 1, horario: "15:00-17:00", idioma: "Inglés", nivel: "Básico 5", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 20, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Intermedio 5 | 15:00-17:00 | Intensivo B", profesor_nombre_id: 1, horario: "15:00-17:00", idioma: "Inglés", nivel: "Intermedio 5", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 17, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "Elvia Ángeles Aldana", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 3 | 17:00-19:00 | Intensivo B", profesor_nombre_id: 1, horario: "17:00-19:00", idioma: "Inglés", nivel: "Básico 3", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 15, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "Elvia Ángeles Aldana", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 4 | 17:00-19:00 | Intensivo B", profesor_nombre_id: 1, horario: "17:00-19:00", idioma: "Inglés", nivel: "Básico 4", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 17, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "Elvia Ángeles Aldana", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 4 | 19:00-21:00 | Intensivo B", profesor_nombre_id: 1, horario: "19:00-21:00", idioma: "Inglés", nivel: "Básico 4", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "16 - Enero,10 - Febrero", user_id: 17, lugar: "", fecha: "", centro: "", tipo: "", modalidad: "", cupo: "", duracion: "", cuota: "", clave: "", proyecto: "", institucion_bancaria: "", cuenta: "", titular: "", instructor: "", instructor_rfc: "", instructor_correo: "", jefe_ec: "Elvia Ángeles Aldana", registro: "", referencia: "", habilitar_constancias_grupo: false},
  {nombre: "Inglés | Básico 1 | 09:00-14:00 | Sabatino 1", profesor_nombre_id: nil, horario: "09:00-14:00", idioma: "Inglés", nivel: "Básico 1", estado: "Cerrado", curso: "Sabatino 1", anio: "2017", periodo: "21 de enero al 11 de marzo", user_id: 17, lugar: "Ciudad de México", fecha: "21 de febrero de 2017", centro: "Ingeniero Eugenio Méndez Docurro", tipo: "Curso", modalidad: "Presencial", cupo: "40", duracion: "40", cuota: "$493.50/$985.50", clave: "0853/0854", proyecto: "Cursos extracurriculares de lenguas extranjeras", institucion_bancaria: "BBVA Bancomer", cuenta: "0168358273", titular: "Fondo de investigación científica y desarrollo tecnológico del IPN", instructor: "17", instructor_rfc: "17", instructor_correo: "17", jefe_ec: "M. en C. Elvia Ángeles Aldana", registro: "DFLE-CELEX02I-Act-15", referencia: "", habilitar_constancias_grupo: true},
  {nombre: "Inglés | Básico 2 | 09:00-11:00 | Intensivo B", profesor_nombre_id: nil, horario: "09:00-11:00", idioma: "Inglés", nivel: "Básico 2", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "20 de febrero al 17 de marzo", user_id: 21, lugar: "Ciudad de México", fecha: "", centro: "Ingeniero Eugenio Méndez Docurro", tipo: "Curso", modalidad: "Presencial", cupo: "20", duracion: "40", cuota: "$493.50/$985.50", clave: "0853/0854", proyecto: "Cursos extracurriculares de lenguas extranjeras", institucion_bancaria: "BBVA Bancomer", cuenta: "0168358273", titular: "Fondo de investigación científica y desarrollo tecnológico del IPN", instructor: "21", instructor_rfc: "21", instructor_correo: "21", jefe_ec: "Elvia Ángeles Aldana", registro: "DFLE-CELEX02I-Act-15", referencia: "", habilitar_constancias_grupo: true},
  {nombre: "Inglés | Intermedio 4 | 12:00-14:00 | Intensivo C", profesor_nombre_id: nil, horario: "12:00-14:00", idioma: "Inglés", nivel: "Intermedio 4", estado: "Cerrado", curso: "Intensivo C", anio: "2017", periodo: "27 de marzo al 29 de abril", user_id: 8, lugar: "Ciudad de México", fecha: "", centro: "Ingeniero Eugenio Méndez Docurro", tipo: "Curso", modalidad: "Presencial", cupo: "20", duracion: "40 hrs", cuota: "$493.50/$985.50", clave: "0853/0854", proyecto: "Cursos extracurriculares de lenguas extranjeras", institucion_bancaria: "BBVA Bancomer", cuenta: "0168358273", titular: "Fondo de investigación científica y desarrollo tecnológico del IPN", instructor: "8", instructor_rfc: "8", instructor_correo: "8", jefe_ec: "Elvia Ángeles Aldana", registro: "DFLE-CELEX02I-Act-15", referencia: "", habilitar_constancias_grupo: true},
  {nombre: "Inglés | Básico 1 | 07:00-09:00 | Intensivo B", profesor_nombre_id: nil, horario: "07:00-09:00", idioma: "Inglés", nivel: "Básico 1", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "20 de febrero al 17 de marzo", user_id: 8, lugar: "Ciudad de México", fecha: "", centro: "Ingeniero Eugenio Méndez Docurro", tipo: "Curso", modalidad: "Presencial", cupo: "25", duracion: "40", cuota: "$493.50/$985.50", clave: "0853/0854", proyecto: "Cursos Extracurriculares de Lenguas Extranjeras", institucion_bancaria: "BBVA Bancomer", cuenta: "0168358273", titular: "Fondo de investigación científica y desarrollo tecnológico del IPN", instructor: "8", instructor_rfc: "8", instructor_correo: "8", jefe_ec: "M. en C. Elvia Ángeles Aldana", registro: "DFLE-CELEX02I-Act-15", referencia: "", habilitar_constancias_grupo: nil},
  {nombre: "Inglés | Básico 1 | 09:00-11:00 | Intensivo B", profesor_nombre_id: nil, horario: "09:00-11:00", idioma: "Inglés", nivel: "Básico 1", estado: "Abierto", curso: "Intensivo B", anio: "2017", periodo: "20 de febrero al 17 de marzo", user_id: 15, lugar: "Ciudad de México", fecha: "", centro: "Ingeniero Eugenio Méndez Docurro", tipo: "Curso", modalidad: "Presencial", cupo: "20", duracion: "40 hrs", cuota: "$493.50/$985.50", clave: "0853/0854", proyecto: "Cursos Extracurriculares de Lenguas Extranjeras", institucion_bancaria: "BBVA Bancomer", cuenta: "0168358273", titular: "Fondo de Investigación Científica y Desarrollo Tecnológico del IPN", instructor: "15", instructor_rfc: "15", instructor_correo: "15", jefe_ec: "M. en C. Elvia Ángeles Aldana", registro: "DFLE-CELEX02I-Act-15", referencia: "", habilitar_constancias_grupo: nil}
])
Horario.create!([
  {hora: "07:00-09:00"},
  {hora: "09:00-11:00"},
  {hora: "11:00-13:00"},
  {hora: "12:00-14:00"},
  {hora: "13:00-15:00"},
  {hora: "15:00-17:00"},
  {hora: "17:00-19:00"},
  {hora: "19:00-21:00"},
  {hora: "09:00-14:00"},
  {hora: "14:00-19:00"}
])
Idioma.create!([
  {idioma: "Inglés"},
  {idioma: "Francés"},
  {idioma: "Italiano"}
])
InscripcionRegistro.create!([
  {nombre: "Mauro Alberto", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "09:00-11:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "mauro@mauro.com", sexo: "Masculino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 25, examen_medio: 90, examen_final: 89, paterno: "Enciso", materno: "Aguilar", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-08 01:40:09", user_id: 13, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Elvia", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "07:00-09:00", opcion_dos: "12:00-14:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "elvia_a_a@hotmail.com", sexo: "Femenino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 25, examen_medio: 94, examen_final: 80, paterno: "Ángeles", materno: "Aldana", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-08 01:41:09", user_id: 12, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Alberto", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "11:00-13:00", opcion_dos: "11:00-13:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "alberto@alberto.com", sexo: "Masculino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 25, examen_medio: 90, examen_final: 78, paterno: "Cruz", materno: "Mendez", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-08 01:42:07", user_id: 11, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Luis Alberto", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "12:00-14:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "luis@hernandez.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: nil, examen_final: nil, paterno: "Hernández", materno: "Calderón", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:29:50", user_id: 29, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "David", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "12:00-14:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "david@carrasco.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 89, paterno: "Carrasco", materno: "Rojas", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:32:34", user_id: 30, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Beatriz Adriana", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "11:00-13:00", opcion_dos: "11:00-13:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "beatriz@cruz.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 98, paterno: "Cruz", materno: "Gutiérrez", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:34:48", user_id: 31, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Mariano", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "13:00-15:00", opcion_dos: "15:00-17:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "mariano@fernandez.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 78, paterno: "Fernández", materno: "Rosas", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:36:39", user_id: 33, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Miguel Ángel", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "11:00-13:00", opcion_dos: "13:00-15:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "miguel@garcia.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 98, paterno: "García", materno: "Gómez", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:37:49", user_id: 34, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Moisés", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "13:00-15:00", opcion_dos: "17:00-19:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "moises@garcia.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 89, paterno: "García", materno: "Pineda", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:40:09", user_id: 35, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Marisela", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "11:00-13:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "marisela@gomez.com", sexo: "Femenino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 100, paterno: "Gómez", materno: "Maldonado", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:45:07", user_id: 36, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Eduardo", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "11:00-13:00", opcion_dos: "15:00-17:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "eduardo@gonzalez.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 80, paterno: "González", materno: "Medina", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:45:58", user_id: 37, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Yosselin", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "09:00-11:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "yosselin@guevara.com", sexo: "Femenino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 89, paterno: "Guevara", materno: "de Gante", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:46:37", user_id: 38, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Rogelio", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "11:00-13:00", opcion_dos: "12:00-14:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "rogelio@hernandez.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 89, paterno: "Hernández", materno: "Martínez", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:47:11", user_id: 39, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Sandra Susana", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "11:00-13:00", opcion_dos: "11:00-13:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "sandra@martinez.com", sexo: "Femenino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 89, paterno: "Martínez", materno: "Castro", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:48:34", user_id: 40, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Gloria", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "09:00-11:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "gloria@mata.com", sexo: "Femenino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 78, paterno: "Mata", materno: "Miranda", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:49:24", user_id: 41, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "José Antonio", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "12:00-14:00", opcion_dos: "15:00-17:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "jose@medina.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 89, paterno: "Medina", materno: "Valdéz", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:50:38", user_id: 42, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Teresa del Carmen", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "07:00-09:00", opcion_dos: "13:00-15:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "teresa@parra.com", sexo: "Femenino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 78, paterno: "Parra", materno: "Toledo", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:51:23", user_id: 43, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Daniela", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "07:00-09:00", opcion_dos: "11:00-13:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "daniela@patino.com", sexo: "Femenino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 100, paterno: "Patiño", materno: "Pérez", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:56:12", user_id: 44, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Julio César", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "12:00-14:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "julio@ramirez.com", sexo: "Masculino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 90, examen_final: 89, paterno: "Ramírez", materno: "Hernández", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:57:04", user_id: 45, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Marcela del Carmen", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "13:00-15:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "marcela@sanchez.com", sexo: "Femenino", cuota: "955.50", movimiento: nil, procedencia: "Otro", grupo_id: 25, examen_medio: 100, examen_final: 99, paterno: "Sánchez", materno: "Chávez", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-09 01:59:19", user_id: 47, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Mauro Alberto", idioma: "Italiano", horario: "07:00-09:00", nivel: "Básico 1", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "11:00-13:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "mauro@mauro.com", sexo: "Masculino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 26, examen_medio: nil, examen_final: nil, paterno: "Enciso", materno: "Aguilar", documentos_validados: false, boleta: "", oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 13, habilitar_constancia: false, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Mauro Alberto", idioma: "Inglés", horario: "07:00-09:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "09:00-11:00", opcion_dos: "12:00-14:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "mauro@mauro.com", sexo: "Masculino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 25, examen_medio: 70, examen_final: 80, paterno: "Enciso", materno: "Aguilar", documentos_validados: false, boleta: "", oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 13, habilitar_constancia: false, habilitar_historial: true, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Mauro Alberto", idioma: "Inglés", horario: "15:00-17:00", nivel: "Intermedio 5", curso: "Intensivo A", opcion_uno: "11:00-13:00", opcion_dos: "12:00-14:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "mauro@mauro.com", sexo: "Masculino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 33, examen_medio: 70, examen_final: 80, paterno: "Enciso", materno: "Aguilar", documentos_validados: false, boleta: "", oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 13, habilitar_constancia: false, habilitar_historial: true, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Beatriz Adriana", idioma: "Inglés", horario: "07:00-09:00", nivel: "Básico 1", curso: "Sabatino 1", opcion_uno: "12:00-14:00", opcion_dos: "13:00-15:00", telefono: "57296000", periodo: "21 de enero al 11 de marzo", correo: "beatriz@cruz.com", sexo: "Femenino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 37, examen_medio: 79, examen_final: 79, paterno: "Cruz", materno: "Gutiérrez", documentos_validados: false, boleta: "", oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 31, habilitar_constancia: false, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Beatriz Adriana", idioma: "Inglés", horario: "07:00-09:00", nivel: "Básico 1", curso: "Sabatino 1", opcion_uno: "13:00-15:00", opcion_dos: "09:00-11:00", telefono: "57296000", periodo: "21 de enero al 11 de marzo", correo: "beatriz@cruz.com", sexo: "Femenino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 37, examen_medio: 79, examen_final: 79, paterno: "Cruz", materno: "Gutiérrez", documentos_validados: false, boleta: "", oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 31, habilitar_constancia: false, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Beatriz Adriana", idioma: "Inglés", horario: "07:00-09:00", nivel: "Básico 1", curso: "Sabatino 1", opcion_uno: "07:00-09:00", opcion_dos: "12:00-14:00", telefono: "57296000", periodo: "21 de enero al 11 de marzo", correo: "beatriz@cruz.com", sexo: "Femenino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 37, examen_medio: 79, examen_final: 79, paterno: "Cruz", materno: "Gutiérrez", documentos_validados: false, boleta: "", oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 31, habilitar_constancia: false, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Gerardo", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "07:00-09:00", opcion_dos: "11:00-13:00", telefono: "5557033791", periodo: "20 de febrero al 17 de marzo", correo: "grarr1533@gmail.com", sexo: "Masculino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Arreola", materno: "Ramírez", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 01:55:26", user_id: 49, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Edgar Ulises", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "09:00-11:00", opcion_dos: "09:00-11:00", telefono: "5527713586", periodo: "20 de febrero al 17 de marzo", correo: "edgar-upiicsa@hotmail.com", sexo: "Masculino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Campos", materno: "Montes", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 01:58:50", user_id: 50, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Elías Salomón", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "07:00-09:00", opcion_dos: "09:00-11:00", telefono: "5539885200", periodo: "20 de febrero al 17 de marzo", correo: "elias_salomon@live.com.mx", sexo: "Masculino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Cruz", materno: "Molina", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:01:08", user_id: 51, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "André Bernardo", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "07:00-09:00", opcion_dos: "11:00-13:00", telefono: "000000000", periodo: "20 de febrero al 17 de marzo", correo: "andrefrancia@live.com.mx", sexo: "Masculino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "García", materno: "Álvarez", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:04:20", user_id: 52, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Boris Agustín", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "09:00-11:00", opcion_dos: "07:00-09:00", telefono: "5569603096", periodo: "20 de febrero al 17 de marzo", correo: "boristorre@yahoo.com.mx", sexo: "Masculino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "García", materno: "Torres", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:06:57", user_id: 53, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "José Benito", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "09:00-11:00", opcion_dos: "09:00-11:00", telefono: "000000000", periodo: "20 de febrero al 17 de marzo", correo: "jose@benito.com", sexo: "Masculino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Gutiérrez", materno: "Álvarado", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:08:31", user_id: 54, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Daniela", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "07:00-09:00", opcion_dos: "07:00-09:00", telefono: "55421304", periodo: "20 de febrero al 17 de marzo", correo: "dani_2300@hotmail.com", sexo: "Femenino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Luna", materno: "Álvarez", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:10:16", user_id: 55, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Javier", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "09:00-11:00", opcion_dos: "11:00-13:00", telefono: "5555264257", periodo: "20 de febrero al 17 de marzo", correo: "javier301912@gmail.com", sexo: "Masculino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Martínez", materno: "Prado", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:12:06", user_id: 56, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "José Antonio", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "09:00-11:00", opcion_dos: "11:00-13:00", telefono: "5521014945", periodo: "20 de febrero al 17 de marzo", correo: "antoniovl.94@hotmail.com", sexo: "Masculino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Moguel", materno: "Ibarra", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:13:39", user_id: 57, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Wendy Itzayán", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "09:00-11:00", opcion_dos: "09:00-11:00", telefono: "5516456605", periodo: "20 de febrero al 17 de marzo", correo: "motriz14@hotmail.com", sexo: "Femenino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Oropeza", materno: "Rodríguez", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:15:46", user_id: 58, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Brenda Isabel", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "09:00-11:00", opcion_dos: "11:00-13:00", telefono: "5516456605", periodo: "20 de febrero al 17 de marzo", correo: "brendaisabel@hotmail.com", sexo: "Femenino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Pérez", materno: "Serrano", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 59, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Ana Damariz", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "07:00-09:00", opcion_dos: "09:00-11:00", telefono: "5516456605", periodo: "20 de febrero al 17 de marzo", correo: "adamarizpz@hotmail.com", sexo: "Femenino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Pérez", materno: "Zaragoza", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:19:52", user_id: 60, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Erik", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "11:00-13:00", opcion_dos: "11:00-13:00", telefono: "5536473136", periodo: "20 de febrero al 17 de marzo", correo: "erikrojo123@hotmail.com", sexo: "Masculino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 27, examen_medio: 89, examen_final: 90, paterno: "Romero", materno: "Castillo", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:21:22", user_id: 61, habilitar_constancia: false, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Alma Nidia", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "07:00-09:00", opcion_dos: "09:00-11:00", telefono: "5547313149", periodo: "20 de febrero al 17 de marzo", correo: "pinchon.color@gmail.com", sexo: "Femenino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Villa", materno: "Rangel", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:22:49", user_id: 62, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Karen Raquel", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 2", curso: "Intensivo B", opcion_uno: "09:00-11:00", opcion_dos: "07:00-09:00", telefono: "54272649", periodo: "20 de febrero al 17 de marzo", correo: "huiloka.glam@gmail.com", sexo: "Femenino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 38, examen_medio: nil, examen_final: nil, paterno: "Huilotl", materno: "Belmares", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-25 02:24:29", user_id: 63, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Daniela", idioma: "Inglés", horario: "07:00-09:00", nivel: "Básico 1", curso: "Sabatino 1", opcion_uno: "11:00-13:00", opcion_dos: "07:00-09:00", telefono: "57296000", periodo: "21 de enero al 11 de marzo", correo: "daniela@moguel.com", sexo: "Femenino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 37, examen_medio: nil, examen_final: nil, paterno: "Moguel", materno: "Prado", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-02-28 02:36:39", user_id: 65, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Mariano", idioma: "Inglés", horario: "07:00-09:00", nivel: "Básico 1", curso: "Sabatino 1", opcion_uno: "", opcion_dos: "", telefono: "5537892548", periodo: "21 de enero al 11 de marzo", correo: "marianopineda@hotmail.com", sexo: "Masculino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 26, examen_medio: nil, examen_final: nil, paterno: "Pineda", materno: "Gómez", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 66, habilitar_constancia: false, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Angelica", idioma: "Inglés", horario: "15:00-17:00", nivel: "Básico 5", curso: "Intensivo B", opcion_uno: "15:00-17:00", opcion_dos: "15:00-17:00", telefono: "", periodo: "16 - Enero,10 - Febrero", correo: "angy8701@outlook.com", sexo: "Femenino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 32, examen_medio: nil, examen_final: nil, paterno: "Torres", materno: "Torres", documentos_validados: false, boleta: nil, oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-03-02 03:04:47", user_id: 67, habilitar_constancia: nil, habilitar_historial: nil, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Daniela", idioma: "Inglés", horario: "15:00-17:00", nivel: "Básico 5", curso: "Intensivo B", opcion_uno: "07:00-09:00", opcion_dos: "07:00-09:00", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "daniela@matias.com", sexo: "Femenino", cuota: "909.50", movimiento: nil, procedencia: "Otro", grupo_id: 26, examen_medio: 80, examen_final: 95, paterno: "Matías", materno: "de Gante", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-03-03 00:07:59", user_id: 68, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: nil},
  {nombre: "Marisela", idioma: "Inglés", horario: "09:00-14:00", nivel: "Básico 1", curso: "Sabatino 1", opcion_uno: "09:00-14:00", opcion_dos: "09:00-14:00", telefono: "57296000", periodo: "21 de enero al 11 de marzo", correo: "marisela@pineda.com", sexo: "Femenino", cuota: "493.50", movimiento: nil, procedencia: "Instituto Politécnico Nacional", grupo_id: 37, examen_medio: 80, examen_final: 80, paterno: "Pineda", materno: "Gómez", documentos_validados: true, boleta: "", oferta_grupo: nil, imagen_file_name: "voucher.jpg", imagen_content_type: "image/jpeg", imagen_file_size: 52285, imagen_updated_at: "2017-03-07 00:34:41", user_id: 71, habilitar_constancia: true, habilitar_historial: false, oficio_prestacion: nil, monto_pagado: "515.00"},
  {nombre: "HECTOR", idioma: "Inglés", horario: "09:00-11:00", nivel: "Básico 1", curso: "Intensivo B", opcion_uno: "", opcion_dos: "", telefono: "57296000", periodo: "16 - Enero,10 - Febrero", correo: "hector@ramirez.com", sexo: "Masculino", cuota: "", movimiento: "", procedencia: "", grupo_id: 27, examen_medio: nil, examen_final: nil, paterno: "RAMIREZ", materno: "VAZQUEZ", documentos_validados: true, boleta: nil, oferta_grupo: nil, imagen_file_name: nil, imagen_content_type: nil, imagen_file_size: nil, imagen_updated_at: nil, user_id: 46, habilitar_constancia: false, habilitar_historial: nil, oficio_prestacion: "", monto_pagado: "510.00"}
])
LugarNombre.create!([
  {nombre: "Ciudad de México"}
])
ModalidadOfertum.create!([
  {nombre: "Presencial"},
  {nombre: "A distancia"}
])
NivelNombre.create!([
  {nivel: "Básico 1"},
  {nivel: "Básico 2"},
  {nivel: "Básico 3"},
  {nivel: "Básico 4"},
  {nivel: "Básico 5"},
  {nivel: "Intermedio 1"},
  {nivel: "Intermedio 2"},
  {nivel: "Intermedio 3"},
  {nivel: "Intermedio 4"},
  {nivel: "Intermedio 5"},
  {nivel: "Avanzado 1"},
  {nivel: "Avanzado 2"},
  {nivel: "Avanzado 3"},
  {nivel: "Avanzado 4"},
  {nivel: "Avanzado 5"},
  {nivel: "Certificación B2.1"},
  {nivel: "Mock 1"}
])
NumeroRegistro.create!([
  {nombre: "DFLE-Curso-CMTKT-CECIEMD-16"},
  {nombre: "DFLE-CELEX02I-Act-15"}
])
Procedencium.create!([
  {procedencia: "Instituto Politécnico Nacional"},
  {procedencia: "Otro"},
  {procedencia: "Prestación"}
])
Proyecto.create!([
  {nombre: "Cursos Extracurriculares de Lenguas Extranjeras"}
])
RegistroCurso.create!([
  {nombre: "Fundamentos de Biblioteconomía: La Biblioteca Manual, Automatizada y Digital", horas: "20", periodo: "Del 20 al 24 de febrero de 2017", temas: "1. Introducción, 2. La biblioteca manual, 3. La biblioteca automatizada, 4. La biblioteca digital, 5. Administración de bibliotecas", instructor: "M. en C. Heberto Reynel Iglesias"}
])
Role.create!([
  {nombre: "Administrador", descripcion: "Administra el sistema"},
  {nombre: "Invitado", descripcion: "Alumno, puede realizar inscripciones"},
  {nombre: "Profesor", descripcion: "Tiene las funciones de instructor"},
  {nombre: "Control escolar", descripcion: "Valida inscripciones"},
  {nombre: "Jefe Educación Continua", descripcion: "Jefe del Departamento de Educación Continua"},
  {nombre: "Director del Centro", descripcion: "Director del Centro de Educación Continua"},
  {nombre: "Coordinación CELEX", descripcion: "Encargado de la coordinación del CELEX"}
])
TipoOfertum.create!([
  {nombre: "Curso"}
])
